export const errorMessages = {
  BOOKMARK_NOT_FOUND: 'error: Bookmark not found',
  BOOKMARK_ALREADY_EXISTS: 'error: Bookmark already exists',
  CODE_IS_INVALID: 'error: verification code is invalid',
  CODE_IS_VALID: 'verification code is valid',
  COMMENT_NOT_FOUND: 'error: Comment not found',
  COMPANY_ALREADY_EXISTS: 'error: Company already exists',
  CMS_ALREADY_EXISTS: 'error: CMS already exists',
  CMS_NOT_EXISTS: 'error: CMS does not exists',
  COMPANY_NOT_EXISTS: 'error: Company does not exists',
  CHAT_NOT_FOUND: 'error: Chat not found',
  CHAT_ALREADY_EXISTS: 'error: Chat already exists',
  EMAIL_ALREADY_IN_USE: 'error: Email already in use',
  EXPERIENCE_NOT_EXISTS: 'error: Experience does not exists',
  GUIDELINE_NOT_EXISTS: 'error: Guideline does not exists',
  GUIDELINE_TYPE_REQUIRED: 'error: Guideline type required',
  GUIDELINE_ALREADY_EXISTS: 'error: Guideline already exists',
  DEPARTMENTS_ROLE_EXIST: 'error: Departments role already exist',
  DEPARTMENTS_ROLE_NOT_FOUND: 'error: Departments role not found',
  INQUIRY_NOT_EXISTS: 'error: Inquiry does not exists',
  INVALID_SMS_CODE: 'error: invalid SMS Code',
  INCORRECT_CREDENTIALS: 'error: incorrect credentials',
  INCORRECT_REQUEST: 'error: Bad Request',
  FEEDBACK_ALREADY_EXISTS: 'error: feedback already exists',
  FILE_IS_REQUIRED: 'error: file is required',
  FILE_MUST_BE_UPLOADED: 'error: file must be uploaded',
  MESSAGE_NOT_EXISTS: 'error: Message does not exists',
  MANAGER_NOT_EXISTS: 'error: Manager does not exists',
  MSG_ALREADY_SENT: 'error: message already sent',
  NOTIFICATION_NOT_FOUND: 'error: Notification not found',
  NOTIFICATION_TYPE_ALREADY_EXIST: 'error: Notification type already exist',
  NOT_EXIST: 'error: not Exist',
  NOTES_ALREADY_EXIST: 'error: User notes already exist',
  NOTES_NOT_EXIST: 'error: User notes does not exist',
  POST_NOT_FOUND: 'error: Post not found',
  SUBSCRIBER_ALREADY_EXISTS: 'error: Subscriber already exists',
  SOMETHING_WENT_WRONG: 'error: Something went wrong',
  SUBSCRIBER_NOT_EXISTS: 'error: Subscriber does not exists',
  TAG_IS_ALREADY_EXIST: 'error: Tag already exist',
  TAG_NOT_FOUND: 'error: Tag not found',
  TWO_AUTH_NOT_CONNECTED: 'error: 2-factor authorized not connected',
  TEAM_NOT_FOUND: 'error: Team not found',
  TOKEN_EXPIRED: 'error: token Expired',
  TOKEN_NOT_EXIST: 'error: Token not exist',
  VOTE_OPTION_NOT_FOUND: 'error: Vote option not found',
  WRONG_EMAIL: 'error: wrong Email',
  USER_ALREADY_BLOCKED: 'error: User already blocked',
  USER_BLOCK_CHAT_CREATING:
    'error: The user has blocked the ability to message him',
  USER_IS_NOT_AUTHOR: 'error: Current user is not author',
  USER_IS_NOT_PARTICIPANT: 'error: Current user is not participant',
  USER_IS_NOT_OWNER: 'error: Current user is not owner',
  USER_IS_NOT_RECIPIENT: 'error: Current user is not recipient',
  USER_ALREADY_EXISTS: 'error: user already exists',
  USER_NOT_FOUND: 'error: User not found',
  REPORT_ALREADY_EXIST: 'error: Report is already exist',
  BLOG_NOT_FOUND: 'error: Blog not found',
  ENTITY_TYPE_IS_NOT_VALID: 'error: Entity type is not valid',
  REPORT_NOT_FOUND: 'error: Report not found',
  INVALID_DATE: 'error: Invalid date',
  REVIEW_NOT_FOUND: 'error: Review not found',
  INVALID_STATUS: 'error: Invalid status',
  RESOURCE_NOT_FOUND: 'error: Resource not found',
  FAQ_NOT_FOUND: 'error: FAQ not found',
  WHY_WORKLOPEDIA_NOT_FOUND: 'error: Why worklopedia not found',
};
